openapi: 3.0.0
info:
  title: order-fulfillment
  version: 0.1.0
  license:
    url: 'https://raw.githubusercontent.com/RektangularStudios/novellia-sdk/main/LICENSE'
    name: MIT
  contact:
    email: contact@rektangularstudios.com
    url: 'https://rektangularstudios.com'
    name: Rektangular Studios
  termsOfService: TODO
servers:
  - url: api.rektangularstudios.com/order-fulfillment
    description: API Gateway
paths:
  /status:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      operationId: get-status
      description: Information regarding status of microservice
  /orders:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: get-orders
      parameters:
        - schema:
            type: string
          in: query
          name: order_id
          description: Identifier for order
          required: true
      description: Gets an order
    post:
      summary: ''
      operationId: post-orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCreated'
      description: Creates an order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/xml:
            schema:
              type: object
              properties: {}
components:
  schemas:
    Status:
      title: Status
      type: object
      description: 'Status of microservice, indicating service availabilities'
      properties:
        maintenance:
          type: boolean
          description: kill-switch to tell users that the backend is not working correctly / is under maintenance
        status:
          type: string
          description: Status string. "UP" if everything is fine.
        errors:
          type: array
          description: List of errors for bad statuses
          items:
            type: string
      required:
        - maintenance
        - status
    Order:
      title: Order
      type: object
      description: Describes a single order
      x-examples:
        order-paid-with-ada:
          products:
            - product_id: PROD-01D78XYFJ1PRM1WPBAOU8JQMNV
              quantity: 4
            - product_id: PROD-01D78XYFJ1PRM1WPBCBT3VHMNV
              quantity: 2
          customer:
            delivery_address: addr1q80u75kavwd5sc7j52x0k8nrqd46540vcjgsvl4fhxjqqs60vcjwf9llp7rv006f0dqyffltyyyzpzl9vct4mp7wjdaspwq39a
          payment:
            payment_address: addr1q80u75kavwd5sc7j52x0k8nrqd46540vcjgsvl4fhxjqqs60vcjwf9llp7rv006f0dqyffltyyyzpzl9vct4mp7wjdaspwq39a
            price_currency_id: ada
            price_amount: 20
            status: AWAITING_PAYMENT
          order_id: ORDER-01D78XYFJ1PRM1WPBCBT3VHMNV
      properties:
        items:
          type: array
          description: ''
          items:
            type: object
            properties:
              product_id:
                type: string
              quantity:
                type: integer
            required:
              - product_id
              - quantity
        customer:
          type: object
          description: ''
          required:
            - delivery_address
          properties:
            delivery_address:
              type: string
              description: Address to deliver tokens to
        payment:
          type: object
          properties:
            payment_address:
              type: string
              description: Address to deposit currency
            price_currency_id:
              type: string
              description: Policy ID of currency
            price_amount:
              description: 'Amount due in currency. Use `number` for fiat, but ADA is lovelace integral'
              type: number
            payment_status:
              type: string
              description: 'Payment status (i.e. waiting, received, ...)'
            actually_paid:
              type: number
              description: Actual amount paid (for partial payments)
          required:
            - price_currency_id
            - price_amount
        order_id:
          type: string
          description: Order ID for future reference
        description:
          type: string
          description: 'Description of order, useful metadata such as presale that occurred, etc.'
        order_status:
          type: string
          description: 'Order status (i.e. awaiting payment, queued, refunded, ...)'
        reservation_expiry:
          type: string
          description: Expiry time of reservation. The order will no longer be payable after this time.
      required:
        - items
        - customer
        - description
    OrderCreated:
      title: OrderCreated
      type: object
      properties:
        order_id:
          type: string
          description: ''
      required:
        - order_id
      description: Response after an order is made
      x-examples:
        example-1:
          order_id: ORDER-01D78XYFJ1PRM1WPBCBT3VHMNV
