/* tslint:disable */
/* eslint-disable */
/**
 * novellia
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A recommended commission for clients that will abide by it
 * @export
 * @interface Commission
 */
export interface Commission {
    /**
     * Name of entity taking commissions
     * @type {string}
     * @memberof Commission
     */
    name: string;
    /**
     * Address to deposit commissions
     * @type {string}
     * @memberof Commission
     */
    address: string;
    /**
     * Recommended commission percentage
     * @type {number}
     * @memberof Commission
     */
    percent?: number;
}

export function CommissionFromJSON(json: any): Commission {
    return CommissionFromJSONTyped(json, false);
}

export function CommissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Commission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'],
        'percent': !exists(json, 'percent') ? undefined : json['percent'],
    };
}

export function CommissionToJSON(value?: Commission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'address': value.address,
        'percent': value.percent,
    };
}


