/* tslint:disable */
/* eslint-disable */
/**
 * novellia
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Generic information required for minter workflows.
 * @export
 * @interface MinterInfo
 */
export interface MinterInfo {
    /**
     * Wallet that pays transaction fee
     * @type {string}
     * @memberof MinterInfo
     */
    walletAddress: string;
    /**
     * Wallet that received minted tokens
     * @type {string}
     * @memberof MinterInfo
     */
    minterDepositAddress: string;
}

export function MinterInfoFromJSON(json: any): MinterInfo {
    return MinterInfoFromJSONTyped(json, false);
}

export function MinterInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinterInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'walletAddress': json['wallet_address'],
        'minterDepositAddress': json['minter_deposit_address'],
    };
}

export function MinterInfoToJSON(value?: MinterInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wallet_address': value.walletAddress,
        'minter_deposit_address': value.minterDepositAddress,
    };
}


