/* tslint:disable */
/* eslint-disable */
/**
 * novellia
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Integer stats
 * @export
 * @interface OccultaNovelliaCharacterStats
 */
export interface OccultaNovelliaCharacterStats {
    /**
     * Damage sustained before dying
     * @type {number}
     * @memberof OccultaNovelliaCharacterStats
     */
    health: number;
    /**
     * Multiplier for damage dealt as defined by attribute moves
     * @type {number}
     * @memberof OccultaNovelliaCharacterStats
     */
    attack: number;
    /**
     * Action points cost per unit of movement
     * @type {number}
     * @memberof OccultaNovelliaCharacterStats
     */
    move: number;
    /**
     * Slots used by character when added to a squad
     * @type {number}
     * @memberof OccultaNovelliaCharacterStats
     */
    slots: number;
}

export function OccultaNovelliaCharacterStatsFromJSON(json: any): OccultaNovelliaCharacterStats {
    return OccultaNovelliaCharacterStatsFromJSONTyped(json, false);
}

export function OccultaNovelliaCharacterStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OccultaNovelliaCharacterStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'health': json['health'],
        'attack': json['attack'],
        'move': json['move'],
        'slots': json['slots'],
    };
}

export function OccultaNovelliaCharacterStatsToJSON(value?: OccultaNovelliaCharacterStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'health': value.health,
        'attack': value.attack,
        'move': value.move,
        'slots': value.slots,
    };
}


