/* tslint:disable */
/* eslint-disable */
/**
 * novellia
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductOrganization
 */
export interface ProductOrganization {
    /**
     * 
     * @type {string}
     * @memberof ProductOrganization
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOrganization
     */
    organizationId: string;
    /**
     * Organization description. This can be markdown.
     * @type {string}
     * @memberof ProductOrganization
     */
    description: string;
}

export function ProductOrganizationFromJSON(json: any): ProductOrganization {
    return ProductOrganizationFromJSONTyped(json, false);
}

export function ProductOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductOrganization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'organizationId': json['organization_id'],
        'description': json['description'],
    };
}

export function ProductOrganizationToJSON(value?: ProductOrganization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'organization_id': value.organizationId,
        'description': value.description,
    };
}


