/* tslint:disable */
/* eslint-disable */
/**
 * novellia
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenSearch
 */
export interface TokenSearch {
    /**
     * List of asset_id, policy_id, or token name
     * @type {Array<string>}
     * @memberof TokenSearch
     */
    cardanoIdentifiers: Array<string>;
}

export function TokenSearchFromJSON(json: any): TokenSearch {
    return TokenSearchFromJSONTyped(json, false);
}

export function TokenSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenSearch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardanoIdentifiers': json['cardano_identifiers'],
    };
}

export function TokenSearchToJSON(value?: TokenSearch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cardano_identifiers': value.cardanoIdentifiers,
    };
}


