/*
 * novellia
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.8.0
 * Contact: contact@rektangularstudios.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package novellia

import (
	"encoding/json"
)

// StatusCardano struct for StatusCardano
type StatusCardano struct {
	// whether cardano-graphql is initialized
	Initialized bool `json:"initialized"`
	// cardano-graphql sync percentage, used to gauge when APIs will be available
	SyncPercentage float32 `json:"sync_percentage"`
}

// NewStatusCardano instantiates a new StatusCardano object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusCardano(initialized bool, syncPercentage float32, ) *StatusCardano {
	this := StatusCardano{}
	this.Initialized = initialized
	this.SyncPercentage = syncPercentage
	return &this
}

// NewStatusCardanoWithDefaults instantiates a new StatusCardano object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusCardanoWithDefaults() *StatusCardano {
	this := StatusCardano{}
	return &this
}

// GetInitialized returns the Initialized field value
func (o *StatusCardano) GetInitialized() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.Initialized
}

// GetInitializedOk returns a tuple with the Initialized field value
// and a boolean to check if the value has been set.
func (o *StatusCardano) GetInitializedOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Initialized, true
}

// SetInitialized sets field value
func (o *StatusCardano) SetInitialized(v bool) {
	o.Initialized = v
}

// GetSyncPercentage returns the SyncPercentage field value
func (o *StatusCardano) GetSyncPercentage() float32 {
	if o == nil  {
		var ret float32
		return ret
	}

	return o.SyncPercentage
}

// GetSyncPercentageOk returns a tuple with the SyncPercentage field value
// and a boolean to check if the value has been set.
func (o *StatusCardano) GetSyncPercentageOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SyncPercentage, true
}

// SetSyncPercentage sets field value
func (o *StatusCardano) SetSyncPercentage(v float32) {
	o.SyncPercentage = v
}

func (o StatusCardano) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["initialized"] = o.Initialized
	}
	if true {
		toSerialize["sync_percentage"] = o.SyncPercentage
	}
	return json.Marshal(toSerialize)
}

type NullableStatusCardano struct {
	value *StatusCardano
	isSet bool
}

func (v NullableStatusCardano) Get() *StatusCardano {
	return v.value
}

func (v *NullableStatusCardano) Set(val *StatusCardano) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusCardano) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusCardano) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusCardano(val *StatusCardano) *NullableStatusCardano {
	return &NullableStatusCardano{value: val, isSet: true}
}

func (v NullableStatusCardano) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusCardano) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


