/*
 * novellia
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.8.0
 * Contact: contact@rektangularstudios.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package novellia

import (
	"encoding/json"
)

// NativeToken Definitions required to reference a native token
type NativeToken struct {
	// On-chain policy-id
	PolicyId string `json:"policy_id"`
	// On-chain asset-id
	AssetId string `json:"asset_id"`
}

// NewNativeToken instantiates a new NativeToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNativeToken(policyId string, assetId string, ) *NativeToken {
	this := NativeToken{}
	this.PolicyId = policyId
	this.AssetId = assetId
	return &this
}

// NewNativeTokenWithDefaults instantiates a new NativeToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNativeTokenWithDefaults() *NativeToken {
	this := NativeToken{}
	return &this
}

// GetPolicyId returns the PolicyId field value
func (o *NativeToken) GetPolicyId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.PolicyId
}

// GetPolicyIdOk returns a tuple with the PolicyId field value
// and a boolean to check if the value has been set.
func (o *NativeToken) GetPolicyIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PolicyId, true
}

// SetPolicyId sets field value
func (o *NativeToken) SetPolicyId(v string) {
	o.PolicyId = v
}

// GetAssetId returns the AssetId field value
func (o *NativeToken) GetAssetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *NativeToken) GetAssetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *NativeToken) SetAssetId(v string) {
	o.AssetId = v
}

func (o NativeToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["policy_id"] = o.PolicyId
	}
	if true {
		toSerialize["asset_id"] = o.AssetId
	}
	return json.Marshal(toSerialize)
}

type NullableNativeToken struct {
	value *NativeToken
	isSet bool
}

func (v NullableNativeToken) Get() *NativeToken {
	return v.value
}

func (v *NullableNativeToken) Set(val *NativeToken) {
	v.value = val
	v.isSet = true
}

func (v NullableNativeToken) IsSet() bool {
	return v.isSet
}

func (v *NullableNativeToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNativeToken(val *NativeToken) *NullableNativeToken {
	return &NullableNativeToken{value: val, isSet: true}
}

func (v NullableNativeToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNativeToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


