/*
 * novellia
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.8.0
 * Contact: contact@rektangularstudios.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package novellia

import (
	"encoding/json"
)

// NovelliaStandardToken Novellia Token Standard on-chain metadata
type NovelliaStandardToken struct {
	// Attribution of rights.
	Copyright string `json:"copyright"`
	// List of publishers or entities involved in token creation. Useful for onlookers to determine token origin. These can be URLs.
	Publisher []string `json:"publisher"`
	// Token version. May have future use such as for clients optionally using later metadata iterations.
	Version int32 `json:"version"`
	// List of extensions for parser to understand feature set. This may be empty, in which case the token is interpreted as just a 721 token.
	Extension []string `json:"extension"`
	// Token number in a set. Redundant field which makes no sense for tokens without a total-order.
	Id int32 `json:"id"`
	// Display name for token.
	Name string `json:"name"`
	// Image URL without source redundancy.
	Image string `json:"image"`
	Description DescriptionSet `json:"description"`
	Resource []OffChainResource `json:"resource"`
	Commission *[]Commission `json:"commission,omitempty"`
	NativeToken NativeToken `json:"native_token"`
	// Identifies the version of the specification in use.
	NovelliaVersion int32 `json:"novellia_version"`
	// Tags for sorting and filtering. \"nsfw\" indicates NSFW content
	Tags []string `json:"tags"`
}

// NewNovelliaStandardToken instantiates a new NovelliaStandardToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNovelliaStandardToken(copyright string, publisher []string, version int32, extension []string, id int32, name string, image string, description DescriptionSet, resource []OffChainResource, nativeToken NativeToken, novelliaVersion int32, tags []string, ) *NovelliaStandardToken {
	this := NovelliaStandardToken{}
	this.Copyright = copyright
	this.Publisher = publisher
	this.Version = version
	this.Extension = extension
	this.Id = id
	this.Name = name
	this.Image = image
	this.Description = description
	this.Resource = resource
	this.NativeToken = nativeToken
	this.NovelliaVersion = novelliaVersion
	this.Tags = tags
	return &this
}

// NewNovelliaStandardTokenWithDefaults instantiates a new NovelliaStandardToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNovelliaStandardTokenWithDefaults() *NovelliaStandardToken {
	this := NovelliaStandardToken{}
	return &this
}

// GetCopyright returns the Copyright field value
func (o *NovelliaStandardToken) GetCopyright() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Copyright
}

// GetCopyrightOk returns a tuple with the Copyright field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetCopyrightOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Copyright, true
}

// SetCopyright sets field value
func (o *NovelliaStandardToken) SetCopyright(v string) {
	o.Copyright = v
}

// GetPublisher returns the Publisher field value
func (o *NovelliaStandardToken) GetPublisher() []string {
	if o == nil  {
		var ret []string
		return ret
	}

	return o.Publisher
}

// GetPublisherOk returns a tuple with the Publisher field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetPublisherOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Publisher, true
}

// SetPublisher sets field value
func (o *NovelliaStandardToken) SetPublisher(v []string) {
	o.Publisher = v
}

// GetVersion returns the Version field value
func (o *NovelliaStandardToken) GetVersion() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetVersionOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *NovelliaStandardToken) SetVersion(v int32) {
	o.Version = v
}

// GetExtension returns the Extension field value
func (o *NovelliaStandardToken) GetExtension() []string {
	if o == nil  {
		var ret []string
		return ret
	}

	return o.Extension
}

// GetExtensionOk returns a tuple with the Extension field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetExtensionOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Extension, true
}

// SetExtension sets field value
func (o *NovelliaStandardToken) SetExtension(v []string) {
	o.Extension = v
}

// GetId returns the Id field value
func (o *NovelliaStandardToken) GetId() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NovelliaStandardToken) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *NovelliaStandardToken) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NovelliaStandardToken) SetName(v string) {
	o.Name = v
}

// GetImage returns the Image field value
func (o *NovelliaStandardToken) GetImage() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetImageOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *NovelliaStandardToken) SetImage(v string) {
	o.Image = v
}

// GetDescription returns the Description field value
func (o *NovelliaStandardToken) GetDescription() DescriptionSet {
	if o == nil  {
		var ret DescriptionSet
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetDescriptionOk() (*DescriptionSet, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *NovelliaStandardToken) SetDescription(v DescriptionSet) {
	o.Description = v
}

// GetResource returns the Resource field value
func (o *NovelliaStandardToken) GetResource() []OffChainResource {
	if o == nil  {
		var ret []OffChainResource
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetResourceOk() (*[]OffChainResource, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *NovelliaStandardToken) SetResource(v []OffChainResource) {
	o.Resource = v
}

// GetCommission returns the Commission field value if set, zero value otherwise.
func (o *NovelliaStandardToken) GetCommission() []Commission {
	if o == nil || o.Commission == nil {
		var ret []Commission
		return ret
	}
	return *o.Commission
}

// GetCommissionOk returns a tuple with the Commission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetCommissionOk() (*[]Commission, bool) {
	if o == nil || o.Commission == nil {
		return nil, false
	}
	return o.Commission, true
}

// HasCommission returns a boolean if a field has been set.
func (o *NovelliaStandardToken) HasCommission() bool {
	if o != nil && o.Commission != nil {
		return true
	}

	return false
}

// SetCommission gets a reference to the given []Commission and assigns it to the Commission field.
func (o *NovelliaStandardToken) SetCommission(v []Commission) {
	o.Commission = &v
}

// GetNativeToken returns the NativeToken field value
func (o *NovelliaStandardToken) GetNativeToken() NativeToken {
	if o == nil  {
		var ret NativeToken
		return ret
	}

	return o.NativeToken
}

// GetNativeTokenOk returns a tuple with the NativeToken field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetNativeTokenOk() (*NativeToken, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NativeToken, true
}

// SetNativeToken sets field value
func (o *NovelliaStandardToken) SetNativeToken(v NativeToken) {
	o.NativeToken = v
}

// GetNovelliaVersion returns the NovelliaVersion field value
func (o *NovelliaStandardToken) GetNovelliaVersion() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.NovelliaVersion
}

// GetNovelliaVersionOk returns a tuple with the NovelliaVersion field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetNovelliaVersionOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NovelliaVersion, true
}

// SetNovelliaVersion sets field value
func (o *NovelliaStandardToken) SetNovelliaVersion(v int32) {
	o.NovelliaVersion = v
}

// GetTags returns the Tags field value
func (o *NovelliaStandardToken) GetTags() []string {
	if o == nil  {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *NovelliaStandardToken) GetTagsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *NovelliaStandardToken) SetTags(v []string) {
	o.Tags = v
}

func (o NovelliaStandardToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["copyright"] = o.Copyright
	}
	if true {
		toSerialize["publisher"] = o.Publisher
	}
	if true {
		toSerialize["version"] = o.Version
	}
	if true {
		toSerialize["extension"] = o.Extension
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["image"] = o.Image
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["resource"] = o.Resource
	}
	if o.Commission != nil {
		toSerialize["commission"] = o.Commission
	}
	if true {
		toSerialize["native_token"] = o.NativeToken
	}
	if true {
		toSerialize["novellia_version"] = o.NovelliaVersion
	}
	if true {
		toSerialize["tags"] = o.Tags
	}
	return json.Marshal(toSerialize)
}

type NullableNovelliaStandardToken struct {
	value *NovelliaStandardToken
	isSet bool
}

func (v NullableNovelliaStandardToken) Get() *NovelliaStandardToken {
	return v.value
}

func (v *NullableNovelliaStandardToken) Set(val *NovelliaStandardToken) {
	v.value = val
	v.isSet = true
}

func (v NullableNovelliaStandardToken) IsSet() bool {
	return v.isSet
}

func (v *NullableNovelliaStandardToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNovelliaStandardToken(val *NovelliaStandardToken) *NullableNovelliaStandardToken {
	return &NullableNovelliaStandardToken{value: val, isSet: true}
}

func (v NullableNovelliaStandardToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNovelliaStandardToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


