/* tslint:disable */
/* eslint-disable */
/**
 * order-fulfillment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderCustomer,
    OrderCustomerFromJSON,
    OrderCustomerFromJSONTyped,
    OrderCustomerToJSON,
    OrderItems,
    OrderItemsFromJSON,
    OrderItemsFromJSONTyped,
    OrderItemsToJSON,
    OrderPayment,
    OrderPaymentFromJSON,
    OrderPaymentFromJSONTyped,
    OrderPaymentToJSON,
} from './';

/**
 * Describes a single order
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * 
     * @type {Array<OrderItems>}
     * @memberof Order
     */
    items: Array<OrderItems>;
    /**
     * 
     * @type {OrderCustomer}
     * @memberof Order
     */
    customer: OrderCustomer;
    /**
     * 
     * @type {OrderPayment}
     * @memberof Order
     */
    payment?: OrderPayment;
    /**
     * Order ID for future reference
     * @type {string}
     * @memberof Order
     */
    orderId: string;
    /**
     * Description of order, useful metadata such as presale that occurred, etc.
     * @type {string}
     * @memberof Order
     */
    description: string;
    /**
     * Order status (i.e. awaiting payment, queued, refunded, ...)
     * @type {string}
     * @memberof Order
     */
    orderStatus: string;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrderItemsFromJSON)),
        'customer': OrderCustomerFromJSON(json['customer']),
        'payment': !exists(json, 'payment') ? undefined : OrderPaymentFromJSON(json['payment']),
        'orderId': json['order_id'],
        'description': json['description'],
        'orderStatus': json['order_status'],
    };
}

export function OrderToJSON(value?: Order | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(OrderItemsToJSON)),
        'customer': OrderCustomerToJSON(value.customer),
        'payment': OrderPaymentToJSON(value.payment),
        'order_id': value.orderId,
        'description': value.description,
        'order_status': value.orderStatus,
    };
}


