/* tslint:disable */
/* eslint-disable */
/**
 * order-fulfillment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItems
 */
export interface OrderItems {
    /**
     * 
     * @type {string}
     * @memberof OrderItems
     */
    productId: string;
    /**
     * 
     * @type {number}
     * @memberof OrderItems
     */
    quantity: number;
}

export function OrderItemsFromJSON(json: any): OrderItems {
    return OrderItemsFromJSONTyped(json, false);
}

export function OrderItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': json['product_id'],
        'quantity': json['quantity'],
    };
}

export function OrderItemsToJSON(value?: OrderItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product_id': value.productId,
        'quantity': value.quantity,
    };
}


