/* tslint:disable */
/* eslint-disable */
/**
 * novellia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Attribution information for artist, sculptor, whoever.
 * @export
 * @interface Attribution
 */
export interface Attribution {
    /**
     * Name to give attribution to
     * @type {string}
     * @memberof Attribution
     */
    authorName: string;
    /**
     * URLs to portfolios, websites, etc.
     * @type {Array<string>}
     * @memberof Attribution
     */
    url: Array<string>;
    /**
     * Description of work attributed
     * @type {string}
     * @memberof Attribution
     */
    workAttributed: string;
}

export function AttributionFromJSON(json: any): Attribution {
    return AttributionFromJSONTyped(json, false);
}

export function AttributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attribution {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorName': json['author_name'],
        'url': json['url'],
        'workAttributed': json['work_attributed'],
    };
}

export function AttributionToJSON(value?: Attribution | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author_name': value.authorName,
        'url': value.url,
        'work_attributed': value.workAttributed,
    };
}


