/* tslint:disable */
/* eslint-disable */
/**
 * novellia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Status of Cardano for determining availability of other endpoints
 * @export
 * @interface CardanoStatus
 */
export interface CardanoStatus {
    /**
     * Whether Cardano APIs are available / Cardano is fully synced
     * @type {boolean}
     * @memberof CardanoStatus
     */
    initialized: boolean;
    /**
     * Cardano sync percentage for progress estimation
     * @type {number}
     * @memberof CardanoStatus
     */
    syncPercentage: number;
}

export function CardanoStatusFromJSON(json: any): CardanoStatus {
    return CardanoStatusFromJSONTyped(json, false);
}

export function CardanoStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardanoStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'initialized': json['initialized'],
        'syncPercentage': json['sync_percentage'],
    };
}

export function CardanoStatusToJSON(value?: CardanoStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'initialized': value.initialized,
        'sync_percentage': value.syncPercentage,
    };
}


