/* tslint:disable */
/* eslint-disable */
/**
 * novellia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Describes a single order / transaction
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * Unique identifier of product
     * @type {number}
     * @memberof Order
     */
    productId: number;
    /**
     * Number of product purchased in order
     * @type {number}
     * @memberof Order
     */
    orderSize: number;
    /**
     * Currency product is priced with
     * @type {string}
     * @memberof Order
     */
    currencyPolicyId: string;
    /**
     * Price for a single item of product type
     * @type {number}
     * @memberof Order
     */
    unitPrice: number;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': json['product_id'],
        'orderSize': json['order_size'],
        'currencyPolicyId': json['currency_policy_id'],
        'unitPrice': json['unit_price'],
    };
}

export function OrderToJSON(value?: Order | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product_id': value.productId,
        'order_size': value.orderSize,
        'currency_policy_id': value.currencyPolicyId,
        'unit_price': value.unitPrice,
    };
}


