/* tslint:disable */
/* eslint-disable */
/**
 * novellia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Details for generic products, standalone without asset resource or specific loader
 * @export
 * @interface ProductProduct
 */
export interface ProductProduct {
    /**
     * URLs to image to display on overview
     * @type {Array<string>}
     * @memberof ProductProduct
     */
    overviewImageUrls: Array<string>;
    /**
     * Token policy ID to refer to blockchain
     * @type {string}
     * @memberof ProductProduct
     */
    tokenPolicyId: string;
    /**
     * Short description of token
     * @type {string}
     * @memberof ProductProduct
     */
    description: string;
    /**
     * Readable name of product
     * @type {string}
     * @memberof ProductProduct
     */
    name: string;
    /**
     * Unique identifier of product
     * @type {number}
     * @memberof ProductProduct
     */
    productId: number;
}

export function ProductProductFromJSON(json: any): ProductProduct {
    return ProductProductFromJSONTyped(json, false);
}

export function ProductProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'overviewImageUrls': json['overview_image_urls'],
        'tokenPolicyId': json['token_policy_id'],
        'description': json['description'],
        'name': json['name'],
        'productId': json['product_id'],
    };
}

export function ProductProductToJSON(value?: ProductProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'overview_image_urls': value.overviewImageUrls,
        'token_policy_id': value.tokenPolicyId,
        'description': value.description,
        'name': value.name,
        'product_id': value.productId,
    };
}


