/* tslint:disable */
/* eslint-disable */
/**
 * novellia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Artist attribution
 * @export
 * @interface ProductArtist
 */
export interface ProductArtist {
    /**
     * Name of artist for token asset
     * @type {string}
     * @memberof ProductArtist
     */
    name?: string;
    /**
     * URLs to learn more about artist (e.g. portfolio). These can point to different places.
     * @type {Array<string>}
     * @memberof ProductArtist
     */
    urls?: Array<string>;
}

export function ProductArtistFromJSON(json: any): ProductArtist {
    return ProductArtistFromJSONTyped(json, false);
}

export function ProductArtistFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductArtist {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'urls': !exists(json, 'urls') ? undefined : json['urls'],
    };
}

export function ProductArtistToJSON(value?: ProductArtist | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'urls': value.urls,
    };
}


