/* tslint:disable */
/* eslint-disable */
/**
 * novellia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Filterable data regarding product
 * @export
 * @interface ProductMetadata
 */
export interface ProductMetadata {
    /**
     * Filterable tags describing the token
     * @type {Array<string>}
     * @memberof ProductMetadata
     */
    tags?: Array<string>;
    /**
     * When the token was listed
     * @type {string}
     * @memberof ProductMetadata
     */
    dateListed: string;
}

export function ProductMetadataFromJSON(json: any): ProductMetadata {
    return ProductMetadataFromJSONTyped(json, false);
}

export function ProductMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'dateListed': json['date_listed'],
    };
}

export function ProductMetadataToJSON(value?: ProductMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags,
        'date_listed': value.dateListed,
    };
}


