/* tslint:disable */
/* eslint-disable */
/**
 * novellia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Extended721Token,
    Extended721TokenFromJSON,
    Extended721TokenFromJSONTyped,
    Extended721TokenToJSON,
    NativeToken,
    NativeTokenFromJSON,
    NativeTokenFromJSONTyped,
    NativeTokenToJSON,
    NovelliaStandardToken,
    NovelliaStandardTokenFromJSON,
    NovelliaStandardTokenFromJSONTyped,
    NovelliaStandardTokenToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductImmutable
 */
export interface ProductImmutable {
    /**
     * 
     * @type {Extended721Token}
     * @memberof ProductImmutable
     */
    extended721Token?: Extended721Token;
    /**
     * 
     * @type {NovelliaStandardToken}
     * @memberof ProductImmutable
     */
    novelliaStandardToken?: NovelliaStandardToken;
    /**
     * 
     * @type {NativeToken}
     * @memberof ProductImmutable
     */
    nativeToken?: NativeToken;
}

export function ProductImmutableFromJSON(json: any): ProductImmutable {
    return ProductImmutableFromJSONTyped(json, false);
}

export function ProductImmutableFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductImmutable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extended721Token': !exists(json, 'extended_721_token') ? undefined : Extended721TokenFromJSON(json['extended_721_token']),
        'novelliaStandardToken': !exists(json, 'novellia_standard_token') ? undefined : NovelliaStandardTokenFromJSON(json['novellia_standard_token']),
        'nativeToken': !exists(json, 'native_token') ? undefined : NativeTokenFromJSON(json['native_token']),
    };
}

export function ProductImmutableToJSON(value?: ProductImmutable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'extended_721_token': Extended721TokenToJSON(value.extended721Token),
        'novellia_standard_token': NovelliaStandardTokenToJSON(value.novelliaStandardToken),
        'native_token': NativeTokenToJSON(value.nativeToken),
    };
}


