/* tslint:disable */
/* eslint-disable */
/**
 * novellia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: contact@rektangularstudios.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DescriptionSet,
    DescriptionSetFromJSON,
    DescriptionSetFromJSONTyped,
    DescriptionSetToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductProduct
 */
export interface ProductProduct {
    /**
     * Product readable name
     * @type {string}
     * @memberof ProductProduct
     */
    name: string;
    /**
     * 
     * @type {DescriptionSet}
     * @memberof ProductProduct
     */
    description: DescriptionSet;
    /**
     * Unique identfier for product
     * @type {string}
     * @memberof ProductProduct
     */
    productId: string;
}

export function ProductProductFromJSON(json: any): ProductProduct {
    return ProductProductFromJSONTyped(json, false);
}

export function ProductProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': DescriptionSetFromJSON(json['description']),
        'productId': json['product_id'],
    };
}

export function ProductProductToJSON(value?: ProductProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': DescriptionSetToJSON(value.description),
        'product_id': value.productId,
    };
}


