/*
 * order-fulfillment
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.2.0
 * Contact: contact@rektangularstudios.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package order_fulfillment

type OrderCustomer struct {

	// Address to deliver tokens to
	DeliveryAddress string `json:"delivery_address"`
}
